### ISSUE TITLE
Use UDP6 agent - check button not working on BeagleBone

### ISSUE THREAD

**Issue by MichalPoterek** [mcollina/node-coap#319]
Hi in my case when I set active  USE UDP6 agent option in Node Red on BeagleBone and then press button Update - value is not stored. How to repair this issue?

**Comment by JKRhb** [comment]
Are you using the [node-red-contrib-coap](https://github.com/JKRhb/node-red-contrib-coap) module for Node-Red? I that case I would have a look into it. Could you maybe open an issue with your flow there for recreating the issue?

**Comment by MichalPoterek** [comment]
Hi, yes it's node red with contrib  node-red-contrib-coap. I will be appreciated for any help with that as I cannot google to many information about that.

**Comment by MichalPoterek** [comment]
Is there is any manual settings which can override  graphical user interface?

**Comment by JKRhb** [comment]
I now fixed the issue over at `node-red-contrib-coap` and released a new version which should be available soon via the Node-Red dashboard. Feel free to report any more issues you encounter using the module in the `node-red-contrib-coap`  repository. For now, I would close this issue :)

**Comment by MichalPoterek** [comment]
It might be something with Node.js versions.  When I update Node.js to version 14 I notice that when I install node-red-contrib-coap with Managing Palette it show  on green bar that 3 components was installed (including Coap request)- so I was happy but later still see that  I haven't Coap request on left toolbar.  Now I'm upgrading Node.js to version 17 - lets see what would be the result.

**Comment by JKRhb** [comment]
Hmm, okay. Could you maybe also have a look on your Node-RED version? It could be also related to that. All node versions starting with 12 should be supported, however, so I would assume that upgrading to an even newer version shouldn't make that much of a difference.
